# All tools are installed on the Docker image at build time based on the installation_command field
# The execution_command field is used when scanning and is used to generate the report file
# pip, curl and apt-get are available. If you need another package manager,
# you can include their own install command by chaining it (e.g. "apt-get install -y npm && npm install -g semgrep")
# or you can add it as a dependency to the base Dockerfile and then use it in the installation_command
generic_tools:
  - name: Semgrep
    installation_command: pip install semgrep
    execution_command: semgrep --config=auto --json --output {output_file}

  - name: Trivy
    installation_command: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin && trivy fs --download-db-only
    execution_command: trivy fs --format json --output {output_file} .

specific_tools:
  - name: Bandit
    supported_file_extensions: [.py]
    installation_command: pip install bandit
    execution_command: bandit -r . -f json -o {output_file}

  - name: gosec
    #supported_file_extensions: [.go] # commented out to test the checks and logs
    installation_command: apt-get install -y gosec
    execution_command: gosec -fmt=json -out={output_file} ./...
